clusterName: cloudspend-guard-eks
region: eu-west-1
vpcId: vpc-0c026d6a9616caeac

serviceAccount:
  create: true
  name: aws-load-balancer-controller

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi