apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.backend.name }}
  namespace: cloudspend
  labels:
    app.kubernetes.io/name: cloudspend-backend
    app.kubernetes.io/part-of: cloudspend-guard